Implement RFC 7405.
duesee/abnf pull request #21
Opened 2022-09-07 14:11 UTC by timothee-haudebourg

Hi, this PR is to implement case sensitive string introduced by [RFC 7405](https://www.rfc-editor.org/rfc/rfc7405).

2022-09-07 23:28 UTC, duesee commented
Hey @timothee-haudebourg, this looks all very good. Thanks! I will try to review this PR in the following few days. Don't mind the failing license check in CI for now.

2022-09-10 07:38 UTC, duesee commented on Cargo.toml
> +rand_distr        = "0.4"
Add newline at end of file.

2022-09-10 07:39 UTC, duesee commented on src/lib.rs
> +        let char_val = std::fs::read_to_string("examples/assets/char_val.abnf").unwrap();
Can we "inline" that from the file?

2022-09-10 07:40 UTC, duesee commented on examples/assets/char_val.abnf
> +f = %S"BAZ"
Can we "inline" that in the tests?

2022-09-10 07:43 UTC, duesee commented on src/lib.rs
> +    let marker = preceded(char('%'), alt((char('i'), char('I'))));
Hehe, seems you cared about everything! :-) I would not have cared about "%I" and "%S". But... it's what the RFC tells us to do, so ... :+1:

2022-09-10 07:49 UTC, duesee requested changes
Thanks, again! I have only two minor nits. I suspect that you have a usecase for RFC 7405 support? I'll try to release a new version to crates.io later.

2022-10-10 08:49 UTC, timothee-haudebourg commented
@duesee Thanks! Yes we have a use case for it there spruceid/treeldr/pull/35, did you figure out the CI problem? :smile:

2022-10-10 15:57 UTC, duesee commented
Oh, thanks for the reminder! :-) https://github.com/duesee/abnf/pull/22 should fix the failing CI. Could you address the remaining two comments? This will be good to go then 👍🏻

2022-10-20 09:10 UTC, timothee-haudebourg commented on src/lib.rs
> +        let char_val = std::fs::read_to_string("examples/assets/char_val.abnf").unwrap();
I hope the way I inlined it is ok.

2022-10-21 14:20 UTC, timothee-haudebourg commented
@duesee sorry for the delay. Did you have time to see the changes?

2022-10-21 14:27 UTC, duesee commented
No worries. Thanks again for the PR and for taking care of the requested changes! This sohuld be good to go (when CI is happy) :+1:

2022-10-21 14:29 UTC, duesee approved these changes
Changes approved.

2022-10-21 14:41 UTC, merged

2022-10-21 14:43 UTC, duesee commented
I'll update the version and make a new release to crates.io :-)

2022-10-21 15:03 UTC, duesee commented
Here we go https://crates.io/crates/abnf 🎉